-- HILFS-VIEW: RELEVANTE AUSLESUNGEN FÜR DTCs: NUR MINIMALE AUSLESUNGEN PRO WERKSTATTFALL MIT DATEITYP 'D'

create view BMW.HELPER_FAHRZEUG_AUSLESEVORGANG_DTC_CLEAN as
select * 
from BMW.V_VM_FAHRZEUG_AUSLESEVORGANG
join (select
	AV2.FAHRGESTELLNR_7, AV2.WERKSTATTFALL_ID, MIN(AV2.AUSLESEINDEX) AS MININDEX 
	from BMW.V_VM_FAHRZEUG_AUSLESEVORGANG AV2 
	where AV2.DATEITYP='D' 
	group by AV2.FAHRGESTELLNR_7, AV2.WERKSTATTFALL_ID) AVR
on (
	BMW.V_VM_FAHRZEUG_AUSLESEVORGANG.FAHRGESTELLNR_7=AVR.FAHRGESTELLNR_7 and
	BMW.V_VM_FAHRZEUG_AUSLESEVORGANG.WERKSTATTFALL_ID=AVR.WERKSTATTFALL_ID and
	BMW.V_VM_FAHRZEUG_AUSLESEVORGANG.AUSLESEINDEX=AVR.MININDEX)



-- HILFS-VIEW: MASTERDATEN (DATUM VON/BIS) ZU WERKSTATTFALL 
create view BMW.HELPER_WERKSTATTFALL as
select FAHRGESTELLNR_7, WERKSTATTFALL_ID, min(AUSLESEDATUM) as DATE_BEGIN, max(AUSLESEDATUM) as DATE_END 
from BMW.V_VM_FAHRZEUG_AUSLESEVORGANG 
group by FAHRGESTELLNR_7, WERKSTATTFALL_ID;


-- HILFS-VIEW: MASTERDATEN ZU WERKSTATTFALL, BEGINN-DATUM BEI KEY-READ-OUT IN DREI-TAGES-FENSTER VOR AUSLESUNGEN

create view BMW.HELPER_WERKSTATTFALL_COMPLETE as
select 	FAHRGESTELLNR_7, 
		WERKSTATTFALL_ID, 
		case
			when (LESEDATUM is NULL) then DATE_BEGIN
			when (LESEDATUM<DATE_BEGINN) then LESEDATUM
			else DATE_BEGIN		
		end as DATE_BEGIN, 
		DATE_END 
from BMW.HELPER_WERKSTATTFALL
left join BMW.V_VM_FZG_SCHLUESSELDATEN on 
	(V_VM_FZG_SCHLUESSELDATEN.FAHRGESTELLNR_7=HELPER_WERKSTATTFALL.FAHRGESTELLNR_7 and 
	V_VM_FZG_SCHLUESSELDATEN.LESEDATUM<=HELPER_WERKSTATTFALL.DATE_END and
	(HELPER_WERKSTATTFALL.DATE_BEGIN-V_VM_FZG_SCHLUESSELDATEN.LESEDATUM)<3
	)


-- HILFS-VIEW: VALIDE DIAGNOSE-CODES

create view BMW.HELPER_DIAGNOSE_TM_DIAGCODE_CLEAN as
select *
from BMW.V_VM_DIAGNOSE_TM_DIAGCODE
where not ((DIAGNOSE_CODE LIKE '%+_9__' ESCAPE '+') or (DIAGNOSE_CODE LIKE '%+_99+_%' ESCAPE '+')) 
